/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ArrayOfRelatedEntriesInner;
import com.konfigthis.client.model.CategorizedTextListInner;
import com.konfigthis.client.model.Entry;
import com.konfigthis.client.model.GrammaticalFeaturesListInner;
import com.konfigthis.client.model.PronunciationsListInner;
import com.konfigthis.client.model.VariantFormsListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LexicalEntry
 */
public class LexicalEntryTest {
    private final LexicalEntry model = new LexicalEntry();

    /**
     * Model tests for LexicalEntry
     */
    @Test
    public void testLexicalEntry() {
        // TODO: test LexicalEntry
    }

    /**
     * Test the property 'derivativeOf'
     */
    @Test
    public void derivativeOfTest() {
        // TODO: test derivativeOf
    }

    /**
     * Test the property 'derivatives'
     */
    @Test
    public void derivativesTest() {
        // TODO: test derivatives
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

    /**
     * Test the property 'grammaticalFeatures'
     */
    @Test
    public void grammaticalFeaturesTest() {
        // TODO: test grammaticalFeatures
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'lexicalCategory'
     */
    @Test
    public void lexicalCategoryTest() {
        // TODO: test lexicalCategory
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'pronunciations'
     */
    @Test
    public void pronunciationsTest() {
        // TODO: test pronunciations
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'variantForms'
     */
    @Test
    public void variantFormsTest() {
        // TODO: test variantForms
    }

}
