/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PronunciationsListInner
 */
public class PronunciationsListInnerTest {
    private final PronunciationsListInner model = new PronunciationsListInner();

    /**
     * Model tests for PronunciationsListInner
     */
    @Test
    public void testPronunciationsListInner() {
        // TODO: test PronunciationsListInner
    }

    /**
     * Test the property 'audioFile'
     */
    @Test
    public void audioFileTest() {
        // TODO: test audioFile
    }

    /**
     * Test the property 'dialects'
     */
    @Test
    public void dialectsTest() {
        // TODO: test dialects
    }

    /**
     * Test the property 'phoneticNotation'
     */
    @Test
    public void phoneticNotationTest() {
        // TODO: test phoneticNotation
    }

    /**
     * Test the property 'phoneticSpelling'
     */
    @Test
    public void phoneticSpellingTest() {
        // TODO: test phoneticSpelling
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

}
