/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExamplesListInner;
import com.konfigthis.client.model.SynonymsAntonymsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ThesaurusSense
 */
public class ThesaurusSenseTest {
    private final ThesaurusSense model = new ThesaurusSense();

    /**
     * Model tests for ThesaurusSense
     */
    @Test
    public void testThesaurusSense() {
        // TODO: test ThesaurusSense
    }

    /**
     * Test the property 'antonyms'
     */
    @Test
    public void antonymsTest() {
        // TODO: test antonyms
    }

    /**
     * Test the property 'domains'
     */
    @Test
    public void domainsTest() {
        // TODO: test domains
    }

    /**
     * Test the property 'examples'
     */
    @Test
    public void examplesTest() {
        // TODO: test examples
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

    /**
     * Test the property 'registers'
     */
    @Test
    public void registersTest() {
        // TODO: test registers
    }

    /**
     * Test the property 'subsenses'
     */
    @Test
    public void subsensesTest() {
        // TODO: test subsenses
    }

    /**
     * Test the property 'synonyms'
     */
    @Test
    public void synonymsTest() {
        // TODO: test synonyms
    }

}
