/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ThesaurusSense;
import com.konfigthis.client.model.VariantFormsListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ThesaurusEntry
 */
public class ThesaurusEntryTest {
    private final ThesaurusEntry model = new ThesaurusEntry();

    /**
     * Model tests for ThesaurusEntry
     */
    @Test
    public void testThesaurusEntry() {
        // TODO: test ThesaurusEntry
    }

    /**
     * Test the property 'homographNumber'
     */
    @Test
    public void homographNumberTest() {
        // TODO: test homographNumber
    }

    /**
     * Test the property 'senses'
     */
    @Test
    public void sensesTest() {
        // TODO: test senses
    }

    /**
     * Test the property 'variantForms'
     */
    @Test
    public void variantFormsTest() {
        // TODO: test variantForms
    }

}
