/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CategorizedTextListInner;
import com.konfigthis.client.model.GrammaticalFeaturesListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TranslationsListInner
 */
public class TranslationsListInnerTest {
    private final TranslationsListInner model = new TranslationsListInner();

    /**
     * Model tests for TranslationsListInner
     */
    @Test
    public void testTranslationsListInner() {
        // TODO: test TranslationsListInner
    }

    /**
     * Test the property 'domains'
     */
    @Test
    public void domainsTest() {
        // TODO: test domains
    }

    /**
     * Test the property 'grammaticalFeatures'
     */
    @Test
    public void grammaticalFeaturesTest() {
        // TODO: test grammaticalFeatures
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

    /**
     * Test the property 'registers'
     */
    @Test
    public void registersTest() {
        // TODO: test registers
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
