/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A mapping of filters available per endpoints.
 */
@ApiModel(description = "A mapping of filters available per endpoints.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FiltersResults {
  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private List<String> entries = null;

  public static final String SERIALIZED_NAME_INFLECTIONS = "inflections";
  @SerializedName(SERIALIZED_NAME_INFLECTIONS)
  private List<String> inflections = null;

  public static final String SERIALIZED_NAME_TRANSLATIONS = "translations";
  @SerializedName(SERIALIZED_NAME_TRANSLATIONS)
  private List<String> translations = null;

  public static final String SERIALIZED_NAME_WORDLIST = "wordlist";
  @SerializedName(SERIALIZED_NAME_WORDLIST)
  private List<String> wordlist = null;

  public FiltersResults() {
  }

  public FiltersResults entries(List<String> entries) {
    
    
    
    
    this.entries = entries;
    return this;
  }

  public FiltersResults addEntriesItem(String entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEntries() {
    return entries;
  }


  public void setEntries(List<String> entries) {
    
    
    
    this.entries = entries;
  }


  public FiltersResults inflections(List<String> inflections) {
    
    
    
    
    this.inflections = inflections;
    return this;
  }

  public FiltersResults addInflectionsItem(String inflectionsItem) {
    if (this.inflections == null) {
      this.inflections = new ArrayList<>();
    }
    this.inflections.add(inflectionsItem);
    return this;
  }

   /**
   * Get inflections
   * @return inflections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getInflections() {
    return inflections;
  }


  public void setInflections(List<String> inflections) {
    
    
    
    this.inflections = inflections;
  }


  public FiltersResults translations(List<String> translations) {
    
    
    
    
    this.translations = translations;
    return this;
  }

  public FiltersResults addTranslationsItem(String translationsItem) {
    if (this.translations == null) {
      this.translations = new ArrayList<>();
    }
    this.translations.add(translationsItem);
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTranslations() {
    return translations;
  }


  public void setTranslations(List<String> translations) {
    
    
    
    this.translations = translations;
  }


  public FiltersResults wordlist(List<String> wordlist) {
    
    
    
    
    this.wordlist = wordlist;
    return this;
  }

  public FiltersResults addWordlistItem(String wordlistItem) {
    if (this.wordlist == null) {
      this.wordlist = new ArrayList<>();
    }
    this.wordlist.add(wordlistItem);
    return this;
  }

   /**
   * Get wordlist
   * @return wordlist
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getWordlist() {
    return wordlist;
  }


  public void setWordlist(List<String> wordlist) {
    
    
    
    this.wordlist = wordlist;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FiltersResults instance itself
   */
  public FiltersResults putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FiltersResults filtersResults = (FiltersResults) o;
    return Objects.equals(this.entries, filtersResults.entries) &&
        Objects.equals(this.inflections, filtersResults.inflections) &&
        Objects.equals(this.translations, filtersResults.translations) &&
        Objects.equals(this.wordlist, filtersResults.wordlist)&&
        Objects.equals(this.additionalProperties, filtersResults.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, inflections, translations, wordlist, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FiltersResults {\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    inflections: ").append(toIndentedString(inflections)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    wordlist: ").append(toIndentedString(wordlist)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("entries");
    openapiFields.add("inflections");
    openapiFields.add("translations");
    openapiFields.add("wordlist");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FiltersResults
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FiltersResults.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FiltersResults is not found in the empty JSON string", FiltersResults.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("entries") != null && !jsonObj.get("entries").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `entries` to be an array in the JSON string but got `%s`", jsonObj.get("entries").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("inflections") != null && !jsonObj.get("inflections").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `inflections` to be an array in the JSON string but got `%s`", jsonObj.get("inflections").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("translations") != null && !jsonObj.get("translations").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `translations` to be an array in the JSON string but got `%s`", jsonObj.get("translations").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("wordlist") != null && !jsonObj.get("wordlist").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `wordlist` to be an array in the JSON string but got `%s`", jsonObj.get("wordlist").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FiltersResults.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FiltersResults' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FiltersResults> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FiltersResults.class));

       return (TypeAdapter<T>) new TypeAdapter<FiltersResults>() {
           @Override
           public void write(JsonWriter out, FiltersResults value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FiltersResults read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FiltersResults instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FiltersResults given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FiltersResults
  * @throws IOException if the JSON string is invalid with respect to FiltersResults
  */
  public static FiltersResults fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FiltersResults.class);
  }

 /**
  * Convert an instance of FiltersResults to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

