/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A grouping of pronunciation information
 */
@ApiModel(description = "A grouping of pronunciation information")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PronunciationsListInner {
  public static final String SERIALIZED_NAME_AUDIO_FILE = "audioFile";
  @SerializedName(SERIALIZED_NAME_AUDIO_FILE)
  private String audioFile;

  public static final String SERIALIZED_NAME_DIALECTS = "dialects";
  @SerializedName(SERIALIZED_NAME_DIALECTS)
  private List<String> dialects = null;

  public static final String SERIALIZED_NAME_PHONETIC_NOTATION = "phoneticNotation";
  @SerializedName(SERIALIZED_NAME_PHONETIC_NOTATION)
  private String phoneticNotation;

  public static final String SERIALIZED_NAME_PHONETIC_SPELLING = "phoneticSpelling";
  @SerializedName(SERIALIZED_NAME_PHONETIC_SPELLING)
  private String phoneticSpelling;

  public static final String SERIALIZED_NAME_REGIONS = "regions";
  @SerializedName(SERIALIZED_NAME_REGIONS)
  private List<String> regions = null;

  public PronunciationsListInner() {
  }

  public PronunciationsListInner audioFile(String audioFile) {
    
    
    
    
    this.audioFile = audioFile;
    return this;
  }

   /**
   * The URL of the sound file
   * @return audioFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of the sound file")

  public String getAudioFile() {
    return audioFile;
  }


  public void setAudioFile(String audioFile) {
    
    
    
    this.audioFile = audioFile;
  }


  public PronunciationsListInner dialects(List<String> dialects) {
    
    
    
    
    this.dialects = dialects;
    return this;
  }

  public PronunciationsListInner addDialectsItem(String dialectsItem) {
    if (this.dialects == null) {
      this.dialects = new ArrayList<>();
    }
    this.dialects.add(dialectsItem);
    return this;
  }

   /**
   * Get dialects
   * @return dialects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDialects() {
    return dialects;
  }


  public void setDialects(List<String> dialects) {
    
    
    
    this.dialects = dialects;
  }


  public PronunciationsListInner phoneticNotation(String phoneticNotation) {
    
    
    
    
    this.phoneticNotation = phoneticNotation;
    return this;
  }

   /**
   * The alphabetic system used to display the phonetic spelling
   * @return phoneticNotation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The alphabetic system used to display the phonetic spelling")

  public String getPhoneticNotation() {
    return phoneticNotation;
  }


  public void setPhoneticNotation(String phoneticNotation) {
    
    
    
    this.phoneticNotation = phoneticNotation;
  }


  public PronunciationsListInner phoneticSpelling(String phoneticSpelling) {
    
    
    
    
    this.phoneticSpelling = phoneticSpelling;
    return this;
  }

   /**
   * Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
   * @return phoneticSpelling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound")

  public String getPhoneticSpelling() {
    return phoneticSpelling;
  }


  public void setPhoneticSpelling(String phoneticSpelling) {
    
    
    
    this.phoneticSpelling = phoneticSpelling;
  }


  public PronunciationsListInner regions(List<String> regions) {
    
    
    
    
    this.regions = regions;
    return this;
  }

  public PronunciationsListInner addRegionsItem(String regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRegions() {
    return regions;
  }


  public void setRegions(List<String> regions) {
    
    
    
    this.regions = regions;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PronunciationsListInner instance itself
   */
  public PronunciationsListInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PronunciationsListInner pronunciationsListInner = (PronunciationsListInner) o;
    return Objects.equals(this.audioFile, pronunciationsListInner.audioFile) &&
        Objects.equals(this.dialects, pronunciationsListInner.dialects) &&
        Objects.equals(this.phoneticNotation, pronunciationsListInner.phoneticNotation) &&
        Objects.equals(this.phoneticSpelling, pronunciationsListInner.phoneticSpelling) &&
        Objects.equals(this.regions, pronunciationsListInner.regions)&&
        Objects.equals(this.additionalProperties, pronunciationsListInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioFile, dialects, phoneticNotation, phoneticSpelling, regions, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PronunciationsListInner {\n");
    sb.append("    audioFile: ").append(toIndentedString(audioFile)).append("\n");
    sb.append("    dialects: ").append(toIndentedString(dialects)).append("\n");
    sb.append("    phoneticNotation: ").append(toIndentedString(phoneticNotation)).append("\n");
    sb.append("    phoneticSpelling: ").append(toIndentedString(phoneticSpelling)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("audioFile");
    openapiFields.add("dialects");
    openapiFields.add("phoneticNotation");
    openapiFields.add("phoneticSpelling");
    openapiFields.add("regions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PronunciationsListInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PronunciationsListInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PronunciationsListInner is not found in the empty JSON string", PronunciationsListInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("audioFile") != null && !jsonObj.get("audioFile").isJsonNull()) && !jsonObj.get("audioFile").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audioFile` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audioFile").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("dialects") != null && !jsonObj.get("dialects").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `dialects` to be an array in the JSON string but got `%s`", jsonObj.get("dialects").toString()));
      }
      if ((jsonObj.get("phoneticNotation") != null && !jsonObj.get("phoneticNotation").isJsonNull()) && !jsonObj.get("phoneticNotation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phoneticNotation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phoneticNotation").toString()));
      }
      if ((jsonObj.get("phoneticSpelling") != null && !jsonObj.get("phoneticSpelling").isJsonNull()) && !jsonObj.get("phoneticSpelling").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phoneticSpelling` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phoneticSpelling").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("regions") != null && !jsonObj.get("regions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `regions` to be an array in the JSON string but got `%s`", jsonObj.get("regions").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PronunciationsListInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PronunciationsListInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PronunciationsListInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PronunciationsListInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PronunciationsListInner>() {
           @Override
           public void write(JsonWriter out, PronunciationsListInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PronunciationsListInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PronunciationsListInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PronunciationsListInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PronunciationsListInner
  * @throws IOException if the JSON string is invalid with respect to PronunciationsListInner
  */
  public static PronunciationsListInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PronunciationsListInner.class);
  }

 /**
  * Convert an instance of PronunciationsListInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

