/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Frequency information for a given entity
 */
@ApiModel(description = "Frequency information for a given entity")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class StatsWordResultResult {
  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private Integer frequency;

  public static final String SERIALIZED_NAME_LEMMA = "lemma";
  @SerializedName(SERIALIZED_NAME_LEMMA)
  private String lemma;

  public static final String SERIALIZED_NAME_LEXICAL_CATEGORY = "lexicalCategory";
  @SerializedName(SERIALIZED_NAME_LEXICAL_CATEGORY)
  private String lexicalCategory;

  public static final String SERIALIZED_NAME_MATCH_COUNT = "matchCount";
  @SerializedName(SERIALIZED_NAME_MATCH_COUNT)
  private Integer matchCount;

  public static final String SERIALIZED_NAME_NORMALIZED_FREQUENCY = "normalizedFrequency";
  @SerializedName(SERIALIZED_NAME_NORMALIZED_FREQUENCY)
  private Integer normalizedFrequency;

  public static final String SERIALIZED_NAME_TRUE_CASE = "trueCase";
  @SerializedName(SERIALIZED_NAME_TRUE_CASE)
  private String trueCase;

  public static final String SERIALIZED_NAME_WORDFORM = "wordform";
  @SerializedName(SERIALIZED_NAME_WORDFORM)
  private String wordform;

  public StatsWordResultResult() {
  }

  public StatsWordResultResult frequency(Integer frequency) {
    
    
    
    
    this.frequency = frequency;
    return this;
  }

   /**
   * The number of times a word appears in the entire corpus
   * @return frequency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of times a word appears in the entire corpus")

  public Integer getFrequency() {
    return frequency;
  }


  public void setFrequency(Integer frequency) {
    
    
    
    this.frequency = frequency;
  }


  public StatsWordResultResult lemma(String lemma) {
    
    
    
    
    this.lemma = lemma;
    return this;
  }

   /**
   * A lemma of the word (e.g., wordforms \&quot;lay\&quot;, \&quot;laid\&quot; and \&quot;laying\&quot; have all lemma \&quot;lay\&quot;)
   * @return lemma
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A lemma of the word (e.g., wordforms \"lay\", \"laid\" and \"laying\" have all lemma \"lay\")")

  public String getLemma() {
    return lemma;
  }


  public void setLemma(String lemma) {
    
    
    
    this.lemma = lemma;
  }


  public StatsWordResultResult lexicalCategory(String lexicalCategory) {
    
    
    
    
    this.lexicalCategory = lexicalCategory;
    return this;
  }

   /**
   * A lexical category such as &#39;verb&#39; or &#39;noun&#39;
   * @return lexicalCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A lexical category such as 'verb' or 'noun'")

  public String getLexicalCategory() {
    return lexicalCategory;
  }


  public void setLexicalCategory(String lexicalCategory) {
    
    
    
    this.lexicalCategory = lexicalCategory;
  }


  public StatsWordResultResult matchCount(Integer matchCount) {
    
    
    
    
    this.matchCount = matchCount;
    return this;
  }

   /**
   * The number of database records that matched the query params (stated frequency is the sum of the individual frequencies)
   * @return matchCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of database records that matched the query params (stated frequency is the sum of the individual frequencies)")

  public Integer getMatchCount() {
    return matchCount;
  }


  public void setMatchCount(Integer matchCount) {
    
    
    
    this.matchCount = matchCount;
  }


  public StatsWordResultResult normalizedFrequency(Integer normalizedFrequency) {
    
    
    
    
    this.normalizedFrequency = normalizedFrequency;
    return this;
  }

   /**
   * The number of times a word appears on average in 1 million words
   * @return normalizedFrequency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of times a word appears on average in 1 million words")

  public Integer getNormalizedFrequency() {
    return normalizedFrequency;
  }


  public void setNormalizedFrequency(Integer normalizedFrequency) {
    
    
    
    this.normalizedFrequency = normalizedFrequency;
  }


  public StatsWordResultResult trueCase(String trueCase) {
    
    
    
    
    this.trueCase = trueCase;
    return this;
  }

   /**
   * A given written realisation of a an entry (e.g., \&quot;lay\&quot;) usually lower case
   * @return trueCase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A given written realisation of a an entry (e.g., \"lay\") usually lower case")

  public String getTrueCase() {
    return trueCase;
  }


  public void setTrueCase(String trueCase) {
    
    
    
    this.trueCase = trueCase;
  }


  public StatsWordResultResult wordform(String wordform) {
    
    
    
    
    this.wordform = wordform;
    return this;
  }

   /**
   * A given written realisation of a an entry (e.g., \&quot;Lay\&quot;) preserving case
   * @return wordform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A given written realisation of a an entry (e.g., \"Lay\") preserving case")

  public String getWordform() {
    return wordform;
  }


  public void setWordform(String wordform) {
    
    
    
    this.wordform = wordform;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the StatsWordResultResult instance itself
   */
  public StatsWordResultResult putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsWordResultResult statsWordResultResult = (StatsWordResultResult) o;
    return Objects.equals(this.frequency, statsWordResultResult.frequency) &&
        Objects.equals(this.lemma, statsWordResultResult.lemma) &&
        Objects.equals(this.lexicalCategory, statsWordResultResult.lexicalCategory) &&
        Objects.equals(this.matchCount, statsWordResultResult.matchCount) &&
        Objects.equals(this.normalizedFrequency, statsWordResultResult.normalizedFrequency) &&
        Objects.equals(this.trueCase, statsWordResultResult.trueCase) &&
        Objects.equals(this.wordform, statsWordResultResult.wordform)&&
        Objects.equals(this.additionalProperties, statsWordResultResult.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequency, lemma, lexicalCategory, matchCount, normalizedFrequency, trueCase, wordform, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsWordResultResult {\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    lemma: ").append(toIndentedString(lemma)).append("\n");
    sb.append("    lexicalCategory: ").append(toIndentedString(lexicalCategory)).append("\n");
    sb.append("    matchCount: ").append(toIndentedString(matchCount)).append("\n");
    sb.append("    normalizedFrequency: ").append(toIndentedString(normalizedFrequency)).append("\n");
    sb.append("    trueCase: ").append(toIndentedString(trueCase)).append("\n");
    sb.append("    wordform: ").append(toIndentedString(wordform)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("frequency");
    openapiFields.add("lemma");
    openapiFields.add("lexicalCategory");
    openapiFields.add("matchCount");
    openapiFields.add("normalizedFrequency");
    openapiFields.add("trueCase");
    openapiFields.add("wordform");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("frequency");
    openapiRequiredFields.add("matchCount");
    openapiRequiredFields.add("normalizedFrequency");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to StatsWordResultResult
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!StatsWordResultResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StatsWordResultResult is not found in the empty JSON string", StatsWordResultResult.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StatsWordResultResult.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("lemma") != null && !jsonObj.get("lemma").isJsonNull()) && !jsonObj.get("lemma").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lemma` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lemma").toString()));
      }
      if ((jsonObj.get("lexicalCategory") != null && !jsonObj.get("lexicalCategory").isJsonNull()) && !jsonObj.get("lexicalCategory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lexicalCategory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lexicalCategory").toString()));
      }
      if ((jsonObj.get("trueCase") != null && !jsonObj.get("trueCase").isJsonNull()) && !jsonObj.get("trueCase").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trueCase` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trueCase").toString()));
      }
      if ((jsonObj.get("wordform") != null && !jsonObj.get("wordform").isJsonNull()) && !jsonObj.get("wordform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wordform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wordform").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatsWordResultResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatsWordResultResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatsWordResultResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatsWordResultResult.class));

       return (TypeAdapter<T>) new TypeAdapter<StatsWordResultResult>() {
           @Override
           public void write(JsonWriter out, StatsWordResultResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StatsWordResultResult read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             StatsWordResultResult instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StatsWordResultResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StatsWordResultResult
  * @throws IOException if the JSON string is invalid with respect to StatsWordResultResult
  */
  public static StatsWordResultResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatsWordResultResult.class);
  }

 /**
  * Convert an instance of StatsWordResultResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

