/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExamplesListInner;
import com.konfigthis.client.model.SynonymsAntonymsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
 */
@ApiModel(description = "A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ThesaurusSense {
  public static final String SERIALIZED_NAME_ANTONYMS = "antonyms";
  @SerializedName(SERIALIZED_NAME_ANTONYMS)
  private List<SynonymsAntonymsInner> antonyms = null;

  public static final String SERIALIZED_NAME_DOMAINS = "domains";
  @SerializedName(SERIALIZED_NAME_DOMAINS)
  private List<String> domains = null;

  public static final String SERIALIZED_NAME_EXAMPLES = "examples";
  @SerializedName(SERIALIZED_NAME_EXAMPLES)
  private List<ExamplesListInner> examples = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_REGIONS = "regions";
  @SerializedName(SERIALIZED_NAME_REGIONS)
  private List<String> regions = null;

  public static final String SERIALIZED_NAME_REGISTERS = "registers";
  @SerializedName(SERIALIZED_NAME_REGISTERS)
  private List<String> registers = null;

  public static final String SERIALIZED_NAME_SUBSENSES = "subsenses";
  @SerializedName(SERIALIZED_NAME_SUBSENSES)
  private List<ThesaurusSense> subsenses = null;

  public static final String SERIALIZED_NAME_SYNONYMS = "synonyms";
  @SerializedName(SERIALIZED_NAME_SYNONYMS)
  private List<SynonymsAntonymsInner> synonyms = null;

  public ThesaurusSense() {
  }

  public ThesaurusSense antonyms(List<SynonymsAntonymsInner> antonyms) {
    
    
    
    
    this.antonyms = antonyms;
    return this;
  }

  public ThesaurusSense addAntonymsItem(SynonymsAntonymsInner antonymsItem) {
    if (this.antonyms == null) {
      this.antonyms = new ArrayList<>();
    }
    this.antonyms.add(antonymsItem);
    return this;
  }

   /**
   * Get antonyms
   * @return antonyms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SynonymsAntonymsInner> getAntonyms() {
    return antonyms;
  }


  public void setAntonyms(List<SynonymsAntonymsInner> antonyms) {
    
    
    
    this.antonyms = antonyms;
  }


  public ThesaurusSense domains(List<String> domains) {
    
    
    
    
    this.domains = domains;
    return this;
  }

  public ThesaurusSense addDomainsItem(String domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<>();
    }
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDomains() {
    return domains;
  }


  public void setDomains(List<String> domains) {
    
    
    
    this.domains = domains;
  }


  public ThesaurusSense examples(List<ExamplesListInner> examples) {
    
    
    
    
    this.examples = examples;
    return this;
  }

  public ThesaurusSense addExamplesItem(ExamplesListInner examplesItem) {
    if (this.examples == null) {
      this.examples = new ArrayList<>();
    }
    this.examples.add(examplesItem);
    return this;
  }

   /**
   * A list of written or spoken rendering of examples of use of a word or text
   * @return examples
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken rendering of examples of use of a word or text")

  public List<ExamplesListInner> getExamples() {
    return examples;
  }


  public void setExamples(List<ExamplesListInner> examples) {
    
    
    
    this.examples = examples;
  }


  public ThesaurusSense id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * The id of the sense that is required for the delete procedure
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the sense that is required for the delete procedure")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public ThesaurusSense regions(List<String> regions) {
    
    
    
    
    this.regions = regions;
    return this;
  }

  public ThesaurusSense addRegionsItem(String regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRegions() {
    return regions;
  }


  public void setRegions(List<String> regions) {
    
    
    
    this.regions = regions;
  }


  public ThesaurusSense registers(List<String> registers) {
    
    
    
    
    this.registers = registers;
    return this;
  }

  public ThesaurusSense addRegistersItem(String registersItem) {
    if (this.registers == null) {
      this.registers = new ArrayList<>();
    }
    this.registers.add(registersItem);
    return this;
  }

   /**
   * Get registers
   * @return registers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRegisters() {
    return registers;
  }


  public void setRegisters(List<String> registers) {
    
    
    
    this.registers = registers;
  }


  public ThesaurusSense subsenses(List<ThesaurusSense> subsenses) {
    
    
    
    
    this.subsenses = subsenses;
    return this;
  }

  public ThesaurusSense addSubsensesItem(ThesaurusSense subsensesItem) {
    if (this.subsenses == null) {
      this.subsenses = new ArrayList<>();
    }
    this.subsenses.add(subsensesItem);
    return this;
  }

   /**
   * subsenses of word
   * @return subsenses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "subsenses of word")

  public List<ThesaurusSense> getSubsenses() {
    return subsenses;
  }


  public void setSubsenses(List<ThesaurusSense> subsenses) {
    
    
    
    this.subsenses = subsenses;
  }


  public ThesaurusSense synonyms(List<SynonymsAntonymsInner> synonyms) {
    
    
    
    
    this.synonyms = synonyms;
    return this;
  }

  public ThesaurusSense addSynonymsItem(SynonymsAntonymsInner synonymsItem) {
    if (this.synonyms == null) {
      this.synonyms = new ArrayList<>();
    }
    this.synonyms.add(synonymsItem);
    return this;
  }

   /**
   * Get synonyms
   * @return synonyms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SynonymsAntonymsInner> getSynonyms() {
    return synonyms;
  }


  public void setSynonyms(List<SynonymsAntonymsInner> synonyms) {
    
    
    
    this.synonyms = synonyms;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ThesaurusSense instance itself
   */
  public ThesaurusSense putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThesaurusSense thesaurusSense = (ThesaurusSense) o;
    return Objects.equals(this.antonyms, thesaurusSense.antonyms) &&
        Objects.equals(this.domains, thesaurusSense.domains) &&
        Objects.equals(this.examples, thesaurusSense.examples) &&
        Objects.equals(this.id, thesaurusSense.id) &&
        Objects.equals(this.regions, thesaurusSense.regions) &&
        Objects.equals(this.registers, thesaurusSense.registers) &&
        Objects.equals(this.subsenses, thesaurusSense.subsenses) &&
        Objects.equals(this.synonyms, thesaurusSense.synonyms)&&
        Objects.equals(this.additionalProperties, thesaurusSense.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(antonyms, domains, examples, id, regions, registers, subsenses, synonyms, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThesaurusSense {\n");
    sb.append("    antonyms: ").append(toIndentedString(antonyms)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    registers: ").append(toIndentedString(registers)).append("\n");
    sb.append("    subsenses: ").append(toIndentedString(subsenses)).append("\n");
    sb.append("    synonyms: ").append(toIndentedString(synonyms)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("antonyms");
    openapiFields.add("domains");
    openapiFields.add("examples");
    openapiFields.add("id");
    openapiFields.add("regions");
    openapiFields.add("registers");
    openapiFields.add("subsenses");
    openapiFields.add("synonyms");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ThesaurusSense
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ThesaurusSense.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThesaurusSense is not found in the empty JSON string", ThesaurusSense.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("antonyms") != null && !jsonObj.get("antonyms").isJsonNull()) {
        JsonArray jsonArrayantonyms = jsonObj.getAsJsonArray("antonyms");
        if (jsonArrayantonyms != null) {
          // ensure the json data is an array
          if (!jsonObj.get("antonyms").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `antonyms` to be an array in the JSON string but got `%s`", jsonObj.get("antonyms").toString()));
          }

          // validate the optional field `antonyms` (array)
          for (int i = 0; i < jsonArrayantonyms.size(); i++) {
            SynonymsAntonymsInner.validateJsonObject(jsonArrayantonyms.get(i).getAsJsonObject());
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("domains") != null && !jsonObj.get("domains").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domains` to be an array in the JSON string but got `%s`", jsonObj.get("domains").toString()));
      }
      if (jsonObj.get("examples") != null && !jsonObj.get("examples").isJsonNull()) {
        JsonArray jsonArrayexamples = jsonObj.getAsJsonArray("examples");
        if (jsonArrayexamples != null) {
          // ensure the json data is an array
          if (!jsonObj.get("examples").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `examples` to be an array in the JSON string but got `%s`", jsonObj.get("examples").toString()));
          }

          // validate the optional field `examples` (array)
          for (int i = 0; i < jsonArrayexamples.size(); i++) {
            ExamplesListInner.validateJsonObject(jsonArrayexamples.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("regions") != null && !jsonObj.get("regions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `regions` to be an array in the JSON string but got `%s`", jsonObj.get("regions").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("registers") != null && !jsonObj.get("registers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `registers` to be an array in the JSON string but got `%s`", jsonObj.get("registers").toString()));
      }
      if (jsonObj.get("subsenses") != null && !jsonObj.get("subsenses").isJsonNull()) {
        JsonArray jsonArraysubsenses = jsonObj.getAsJsonArray("subsenses");
        if (jsonArraysubsenses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("subsenses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `subsenses` to be an array in the JSON string but got `%s`", jsonObj.get("subsenses").toString()));
          }

          // validate the optional field `subsenses` (array)
          for (int i = 0; i < jsonArraysubsenses.size(); i++) {
            ThesaurusSense.validateJsonObject(jsonArraysubsenses.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("synonyms") != null && !jsonObj.get("synonyms").isJsonNull()) {
        JsonArray jsonArraysynonyms = jsonObj.getAsJsonArray("synonyms");
        if (jsonArraysynonyms != null) {
          // ensure the json data is an array
          if (!jsonObj.get("synonyms").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `synonyms` to be an array in the JSON string but got `%s`", jsonObj.get("synonyms").toString()));
          }

          // validate the optional field `synonyms` (array)
          for (int i = 0; i < jsonArraysynonyms.size(); i++) {
            SynonymsAntonymsInner.validateJsonObject(jsonArraysynonyms.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThesaurusSense.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThesaurusSense' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThesaurusSense> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThesaurusSense.class));

       return (TypeAdapter<T>) new TypeAdapter<ThesaurusSense>() {
           @Override
           public void write(JsonWriter out, ThesaurusSense value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ThesaurusSense read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ThesaurusSense instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ThesaurusSense given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ThesaurusSense
  * @throws IOException if the JSON string is invalid with respect to ThesaurusSense
  */
  public static ThesaurusSense fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThesaurusSense.class);
  }

 /**
  * Convert an instance of ThesaurusSense to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

