/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Wordlist;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Disabled
public class SearchApiTest {

    private static SearchApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SearchApi(apiClient);
    }

    /**
     * Retrieve possible matches to input
     *
     *  Use this to retrieve possible [headword](documentation/glossary?term&#x3D;headword) matches for a given string of text. The results are culculated using headword matching, fuzzy matching, and [lemmatization](documentation/glossary?term&#x3D;lemma)     &lt;div id&#x3D;\&quot;search\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMatchesTest() throws ApiException {
        String sourceLang = null;
        String q = null;
        Boolean prefix = null;
        String regions = null;
        String limit = null;
        String offset = null;
        Wordlist response = api.getMatches(sourceLang)
                .q(q)
                .prefix(prefix)
                .regions(regions)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve possible translation matches to input
     *
     *  Use this to find matches in our translation dictionaries.    &lt;div id&#x3D;\&quot;search_translation\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void possibleTranslationsTest() throws ApiException {
        String sourceSearchLanguage = null;
        String targetSearchLanguage = null;
        String q = null;
        Boolean prefix = null;
        String regions = null;
        String limit = null;
        String offset = null;
        Wordlist response = api.possibleTranslations(sourceSearchLanguage, targetSearchLanguage)
                .q(q)
                .prefix(prefix)
                .regions(regions)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
