/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Thesaurus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ThesaurusApi
 */
@Disabled
public class ThesaurusApiTest {

    private static ThesaurusApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ThesaurusApi(apiClient);
    }

    /**
     * Retrieve words that mean the opposite
     *
     *  Retrieve words that are opposite in meaning to the input word ([antonym](documentation/glossary?term&#x3D;thesaurus)).    &lt;div id&#x3D;\&quot;antonyms\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAntonymsTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        Thesaurus response = api.getAntonyms(sourceLang, wordId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve words that are similar
     *
     *  Use this to retrieve words that are similar in meaning to the input word ([synonym](documentation/glossary?term&#x3D;synonym)).    &lt;div id&#x3D;\&quot;synonyms\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSimilarWordsTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        Thesaurus response = api.getSimilarWords(sourceLang, wordId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve synonyms and antonyms for a given word
     *
     *  Retrieve available [synonyms](documentation/glossary?term&#x3D;thesaurus) and [antonyms](documentation/glossary?term&#x3D;thesaurus) for a given word and language.     &lt;div id&#x3D;\&quot;synonyms_and_antonyms\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSynonymsAntonymsTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        Thesaurus response = api.getSynonymsAntonyms(sourceLang, wordId)
                .execute();
        // TODO: test validations
    }

}
