/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Wordlist;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WordlistApi
 */
@Disabled
public class WordlistApiTest {

    private static WordlistApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new WordlistApi(apiClient);
    }

    /**
     * Retrieve list of words for category with advanced options
     *
     * Use this to apply more complex filters to the [list of words](documentation/glossary?term&#x3D;wordlist). For example, you may only want to filter out words for which all [senses](documentation/glossary?term&#x3D;sense) match the filter, or only its &#39;prime sense&#39;. You can also filter by word length or match by substring (prefix).     &lt;div id&#x3D;\&quot;wordlist_advanced\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAdvancedWordsTest() throws ApiException {
        String sourceLang = null;
        String filtersAdvanced = null;
        String exclude = null;
        String excludeSenses = null;
        String excludePrimeSenses = null;
        String wordLength = null;
        String prefix = null;
        Boolean exact = null;
        String limit = null;
        String offset = null;
        Wordlist response = api.getAdvancedWords(sourceLang, filtersAdvanced)
                .exclude(exclude)
                .excludeSenses(excludeSenses)
                .excludePrimeSenses(excludePrimeSenses)
                .wordLength(wordLength)
                .prefix(prefix)
                .exact(exact)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of words in a category
     *
     *  Use this to retrieve a [list of words](documentation/glossary?term&#x3D;wordlist) for particular [domain](documentation/glossary?term&#x3D;domain), [lexical category](documentation/glossary?term&#x3D;lexicalcategory), [register](documentation/glossary?term&#x3D;registers) and/or [region](documentation/glossary?term&#x3D;regions). View the full list of possible filters using the filters Utility endpoint.  The response only includes [headwords](documentation/glossary?term&#x3D;headword), not all their possible [inflections](documentation/glossary?term&#x3D;inflection). If you require a full [wordlist](documentation/glossary?term&#x3D;wordlist) including [inflected forms](documentation/glossary?term&#x3D;inflection), contact us and we can help.    &lt;div id&#x3D;\&quot;wordlist\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoryWordsTest() throws ApiException {
        String sourceLang = null;
        String filtersBasic = null;
        String limit = null;
        String offset = null;
        Wordlist response = api.getCategoryWords(sourceLang, filtersBasic)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
