/*
 * Oxford Dictionaries
 * Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.Thesaurus;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class ThesaurusApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ThesaurusApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public ThesaurusApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getAppId() == null) {
            throw new IllegalArgumentException("\"app_id\" is required but no API key was provided. Please set \"app_id\" with ApiClient#setAppId(String).");
        }
        if (apiClient.getAppKey() == null) {
            throw new IllegalArgumentException("\"app_key\" is required but no API key was provided. Please set \"app_key\" with ApiClient#setAppKey(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getAntonymsCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/entries/{source_lang}/{word_id}/antonyms"
            .replace("{" + "source_lang" + "}", localVarApiClient.escapeString(sourceLang.toString()))
            .replace("{" + "word_id" + "}", localVarApiClient.escapeString(wordId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "appId", "appKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAntonymsValidateBeforeCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sourceLang' is set
        if (sourceLang == null) {
            throw new ApiException("Missing the required parameter 'sourceLang' when calling getAntonyms(Async)");
        }

        // verify the required parameter 'wordId' is set
        if (wordId == null) {
            throw new ApiException("Missing the required parameter 'wordId' when calling getAntonyms(Async)");
        }

        return getAntonymsCall(sourceLang, wordId, _callback);

    }


    private ApiResponse<Thesaurus> getAntonymsWithHttpInfo(String sourceLang, String wordId) throws ApiException {
        okhttp3.Call localVarCall = getAntonymsValidateBeforeCall(sourceLang, wordId, null);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getAntonymsAsync(String sourceLang, String wordId, final ApiCallback<Thesaurus> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAntonymsValidateBeforeCall(sourceLang, wordId, _callback);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetAntonymsRequestBuilder {
        private final String sourceLang;
        private final String wordId;

        private GetAntonymsRequestBuilder(String sourceLang, String wordId) {
            this.sourceLang = sourceLang;
            this.wordId = wordId;
        }

        /**
         * Build call for getAntonyms
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getAntonymsCall(sourceLang, wordId, _callback);
        }


        /**
         * Execute getAntonyms request
         * @return Thesaurus
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public Thesaurus execute() throws ApiException {
            ApiResponse<Thesaurus> localVarResp = getAntonymsWithHttpInfo(sourceLang, wordId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getAntonyms request with HTTP info returned
         * @return ApiResponse&lt;Thesaurus&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Thesaurus> executeWithHttpInfo() throws ApiException {
            return getAntonymsWithHttpInfo(sourceLang, wordId);
        }

        /**
         * Execute getAntonyms request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Thesaurus> _callback) throws ApiException {
            return getAntonymsAsync(sourceLang, wordId, _callback);
        }
    }

    /**
     * Retrieve words that mean the opposite
     *  Retrieve words that are opposite in meaning to the input word ([antonym](documentation/glossary?term&#x3D;thesaurus)).    &lt;div id&#x3D;\&quot;antonyms\&quot;&gt;&lt;/div&gt; 
     * @param sourceLang IANA language code (required)
     * @param wordId An Entry identifier. Case-sensitive. (required)
     * @return GetAntonymsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
     </table>
     * find more info here
     * @see <a href="https://helloreverb.com/about">Retrieve words that mean the opposite Documentation</a>
     */
    public GetAntonymsRequestBuilder getAntonyms(String sourceLang, String wordId) throws IllegalArgumentException {
        if (sourceLang == null) throw new IllegalArgumentException("\"sourceLang\" is required but got null");
            

        if (wordId == null) throw new IllegalArgumentException("\"wordId\" is required but got null");
            

        return new GetAntonymsRequestBuilder(sourceLang, wordId);
    }
    private okhttp3.Call getSimilarWordsCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/entries/{source_lang}/{word_id}/synonyms"
            .replace("{" + "source_lang" + "}", localVarApiClient.escapeString(sourceLang.toString()))
            .replace("{" + "word_id" + "}", localVarApiClient.escapeString(wordId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "appId", "appKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSimilarWordsValidateBeforeCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sourceLang' is set
        if (sourceLang == null) {
            throw new ApiException("Missing the required parameter 'sourceLang' when calling getSimilarWords(Async)");
        }

        // verify the required parameter 'wordId' is set
        if (wordId == null) {
            throw new ApiException("Missing the required parameter 'wordId' when calling getSimilarWords(Async)");
        }

        return getSimilarWordsCall(sourceLang, wordId, _callback);

    }


    private ApiResponse<Thesaurus> getSimilarWordsWithHttpInfo(String sourceLang, String wordId) throws ApiException {
        okhttp3.Call localVarCall = getSimilarWordsValidateBeforeCall(sourceLang, wordId, null);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getSimilarWordsAsync(String sourceLang, String wordId, final ApiCallback<Thesaurus> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSimilarWordsValidateBeforeCall(sourceLang, wordId, _callback);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetSimilarWordsRequestBuilder {
        private final String sourceLang;
        private final String wordId;

        private GetSimilarWordsRequestBuilder(String sourceLang, String wordId) {
            this.sourceLang = sourceLang;
            this.wordId = wordId;
        }

        /**
         * Build call for getSimilarWords
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getSimilarWordsCall(sourceLang, wordId, _callback);
        }


        /**
         * Execute getSimilarWords request
         * @return Thesaurus
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public Thesaurus execute() throws ApiException {
            ApiResponse<Thesaurus> localVarResp = getSimilarWordsWithHttpInfo(sourceLang, wordId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getSimilarWords request with HTTP info returned
         * @return ApiResponse&lt;Thesaurus&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Thesaurus> executeWithHttpInfo() throws ApiException {
            return getSimilarWordsWithHttpInfo(sourceLang, wordId);
        }

        /**
         * Execute getSimilarWords request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Thesaurus> _callback) throws ApiException {
            return getSimilarWordsAsync(sourceLang, wordId, _callback);
        }
    }

    /**
     * Retrieve words that are similar
     *  Use this to retrieve words that are similar in meaning to the input word ([synonym](documentation/glossary?term&#x3D;synonym)).    &lt;div id&#x3D;\&quot;synonyms\&quot;&gt;&lt;/div&gt; 
     * @param sourceLang IANA language code (required)
     * @param wordId An Entry identifier. Case-sensitive. (required)
     * @return GetSimilarWordsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
     </table>
     * find more info here
     * @see <a href="https://helloreverb.com/about">Retrieve words that are similar Documentation</a>
     */
    public GetSimilarWordsRequestBuilder getSimilarWords(String sourceLang, String wordId) throws IllegalArgumentException {
        if (sourceLang == null) throw new IllegalArgumentException("\"sourceLang\" is required but got null");
            

        if (wordId == null) throw new IllegalArgumentException("\"wordId\" is required but got null");
            

        return new GetSimilarWordsRequestBuilder(sourceLang, wordId);
    }
    private okhttp3.Call getSynonymsAntonymsCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/entries/{source_lang}/{word_id}/synonyms;antonyms"
            .replace("{" + "source_lang" + "}", localVarApiClient.escapeString(sourceLang.toString()))
            .replace("{" + "word_id" + "}", localVarApiClient.escapeString(wordId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "appId", "appKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSynonymsAntonymsValidateBeforeCall(String sourceLang, String wordId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sourceLang' is set
        if (sourceLang == null) {
            throw new ApiException("Missing the required parameter 'sourceLang' when calling getSynonymsAntonyms(Async)");
        }

        // verify the required parameter 'wordId' is set
        if (wordId == null) {
            throw new ApiException("Missing the required parameter 'wordId' when calling getSynonymsAntonyms(Async)");
        }

        return getSynonymsAntonymsCall(sourceLang, wordId, _callback);

    }


    private ApiResponse<Thesaurus> getSynonymsAntonymsWithHttpInfo(String sourceLang, String wordId) throws ApiException {
        okhttp3.Call localVarCall = getSynonymsAntonymsValidateBeforeCall(sourceLang, wordId, null);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getSynonymsAntonymsAsync(String sourceLang, String wordId, final ApiCallback<Thesaurus> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSynonymsAntonymsValidateBeforeCall(sourceLang, wordId, _callback);
        Type localVarReturnType = new TypeToken<Thesaurus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetSynonymsAntonymsRequestBuilder {
        private final String sourceLang;
        private final String wordId;

        private GetSynonymsAntonymsRequestBuilder(String sourceLang, String wordId) {
            this.sourceLang = sourceLang;
            this.wordId = wordId;
        }

        /**
         * Build call for getSynonymsAntonyms
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getSynonymsAntonymsCall(sourceLang, wordId, _callback);
        }


        /**
         * Execute getSynonymsAntonyms request
         * @return Thesaurus
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public Thesaurus execute() throws ApiException {
            ApiResponse<Thesaurus> localVarResp = getSynonymsAntonymsWithHttpInfo(sourceLang, wordId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getSynonymsAntonyms request with HTTP info returned
         * @return ApiResponse&lt;Thesaurus&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Thesaurus> executeWithHttpInfo() throws ApiException {
            return getSynonymsAntonymsWithHttpInfo(sourceLang, wordId);
        }

        /**
         * Execute getSynonymsAntonyms request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
            <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Thesaurus> _callback) throws ApiException {
            return getSynonymsAntonymsAsync(sourceLang, wordId, _callback);
        }
    }

    /**
     * Retrieve synonyms and antonyms for a given word
     *  Retrieve available [synonyms](documentation/glossary?term&#x3D;thesaurus) and [antonyms](documentation/glossary?term&#x3D;thesaurus) for a given word and language.     &lt;div id&#x3D;\&quot;synonyms_and_antonyms\&quot;&gt;&lt;/div&gt; 
     * @param sourceLang IANA language code (required)
     * @param wordId An Entry identifier. Case-sensitive. (required)
     * @return GetSynonymsAntonymsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No entry is found matching supplied id and source_lang or filters are not recognized  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Error. An error occurred while processing the data.  </td><td>  -  </td></tr>
     </table>
     * find more info here
     * @see <a href="https://helloreverb.com/about">Retrieve synonyms and antonyms for a given word Documentation</a>
     */
    public GetSynonymsAntonymsRequestBuilder getSynonymsAntonyms(String sourceLang, String wordId) throws IllegalArgumentException {
        if (sourceLang == null) throw new IllegalArgumentException("\"sourceLang\" is required but got null");
            

        if (wordId == null) throw new IllegalArgumentException("\"wordId\" is required but got null");
            

        return new GetSynonymsAntonymsRequestBuilder(sourceLang, wordId);
    }
}
